#!/bin/sh

#
# Copyright © 2015-2021 the original authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh is
#       noncompliant, but you have some other compliant shell such as ksh or
#       bash, then you need to set the SHELL environment variable to point
#       to that shell before running this script.
#
#       SHELL=/bin/bash ./gradlew
#
#   (2) This script is generated by Gradle. Do not edit it.
#
##############################################################################

# Attempt to set APP_HOME

# Resolve links: $0 may be a link
app_path=$0

# Need this for daisy-chained symlinks.
while
    APP_HOME=${app_path%"${app_path##*/}"}  # leaves a trailing /; empty if no leading path
    [ -h "$app_path" ]
do
    ls=$(ls -ld "$app_path")
    link=${ls#*' -> '}
    case $link in             #(
      /*)   app_path=$link ;; #(
      *)    app_path=$APP_HOME$link ;;
    esac
done

# This is normally unused
# shellcheck disable=SC2034
APP_BASE_NAME=${0##*/}
# Discard cd standard output in case $CDPATH is set (https://github.com/gradle/gradle/issues/25036)
APP_HOME=$( cd "${APP_HOME:-./}" > /dev/null && pwd -P ) || exit

# Use the maximum available file descriptors if possible.
if [ -n "$(command -v ulimit)" ] && [ -n "$(ulimit -n)" ]; then
    ulimit -n "$(ulimit -n)"
fi

# Make sure the classpath isn't dirty with CRLF line endings.
if [ -n "$(uname)" ] && { [ "$(uname)" = "CYGWIN"* ] || [ "$(uname)" = "MINGW"* ] || [ "$(uname)" = "MSYS"* ]; }; then
    CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar$(printf ':%s' "$APP_HOME/gradle/wrapper/"*.jar)
else
    CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar
fi

# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        # IBM's JDK on AIX uses strange locations for the executables
        JAVACMD=$JAVA_HOME/jre/sh/java
    else
        JAVACMD=$JAVA_HOME/bin/java
    fi
    if [ ! -x "$JAVACMD" ] ; then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
else
    JAVACMD=java
    if ! command -v java >/dev/null 2>&1
    then
        die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
fi

# Increase the maximum file descriptors if we can.
if [ -n "$(command -v ulimit)" ] && [ -n "$(ulimit -n)" ]; then
    ulimit -n "$(ulimit -n)"
fi

# Collect all arguments for the java command, stacking in reverse order:
#   * args from the command line
#   * the main class name
#   * -classpath
#   * -D...appname settings
#   * --module-path (only if dedicated home module is specified)
#   * --module (only if dedicated home module is specified)
#   * together with and without parameters from the "JAVA_OPTS %JAVA_OPTS%" and "_JAVA_OPTS %_JAVA_OPTS%" environment variables.

# The Java main class to run.
MAIN_CLASS_NAME=org.gradle.wrapper.GradleWrapperMain

# Collect all arguments for the java command;
#   * $JAVA_OPTS and $GRADLE_OPTS can contain a limited number of arguments,
#   * $DEFAULT_JVM_OPTS can contain a limited number of arguments,
#   * either the JAVA_OPTS or GRADLE_OPTS or DEFAULT_JVM_OPTS can contain a limited
#     number of arguments.
#   * Either the JAVA_OPTS or GRADLE_OPTS must contain the project properties
#     that must be passed to Gradle.
#   * Gradle also needs the project properties from the command line.
#   * The Java main class needs to be specified.
#   * The -classpath is a single argument but we can't use a single quoted string
#     because the path could have spaces.

# Construct a minimal classpath.
base_classpath="$APP_HOME/gradle/wrapper/gradle-wrapper.jar"
classpath="$base_classpath"

# Add the jars in the lib directory if it exists.
if [ -d "$APP_HOME/lib" ]; then
    classpath="$classpath:$APP_HOME/lib"/*
fi

# Determine if a module path is specified.
module_path=""
if [ -n "$JAVA_OPTS" ] && echo "$JAVA_OPTS" | grep -q "\-\-module\-path"; then
    module_path=$(echo "$JAVA_OPTS" | sed -n 's/.*--module-path[= ]*\([^ ]*\).*/\1/p')
elif [ -n "$GRADLE_OPTS" ] && echo "$GRADLE_OPTS" | grep -q "\-\-module\-path"; then
    module_path=$(echo "$GRADLE_OPTS" | sed -n 's/.*--module-path[= ]*\([^ ]*\).*/\1/p')
fi

# If module path is specified, add it to the classpath.
if [ -n "$module_path" ]; then
    classpath="$classpath:$module_path"
fi

# Make sure the classpath doesn't have duplicate entries.
classpath=$(echo "$classpath" | tr ':' '\n' | sort -u | tr '\n' ':')
classpath="${classpath%:}"

set -- \
        "-Dorg.gradle.appname=$APP_BASE_NAME" \
        -classpath "$classpath" \
        "$MAIN_CLASS_NAME" \
        "$@"

# Use "eval" to set variables and avoid splitting issues.
eval set -- "$@"

# Use "exec" to replace the current shell process and avoid child processes.
exec "$JAVACMD" "$@"
